// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsNeedLogin(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NEED_LOGIN.String() && e.Code == 401
}

func ErrorNeedLogin(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_NEED_LOGIN.String(), fmt.Sprintf(format, args...))
}

func IsDbFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DB_FAILED.String() && e.Code == 500
}

func ErrorDbFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DB_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsAppealAudited(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_APPEAL_AUDITED.String() && e.Code == 400
}

func ErrorAppealAudited(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_APPEAL_AUDITED.String(), fmt.Sprintf(format, args...))
}

func IsReviewAppealed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_APPEALED.String() && e.Code == 400
}

func ErrorReviewAppealed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_REVIEW_APPEALED.String(), fmt.Sprintf(format, args...))
}

func IsInvalidParams(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_PARAMS.String() && e.Code == 500
}

func ErrorInvalidParams(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INVALID_PARAMS.String(), fmt.Sprintf(format, args...))
}

func IsOrderReviewed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_ORDER_REVIEWED.String() && e.Code == 400
}

func ErrorOrderReviewed(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_ORDER_REVIEWED.String(), fmt.Sprintf(format, args...))
}

func IsReviewReplied(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_REVIEW_REPLIED.String() && e.Code == 400
}

func ErrorReviewReplied(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_REVIEW_REPLIED.String(), fmt.Sprintf(format, args...))
}
